if v:lang =~ "utf8$" || v:lang =~ "UTF-8$"
   set fileencodings=ucs-bom,utf-8,latin1
endif

set nocompatible
" Utiliser Vim par défaut
set bs=indent,eol,start
" Backspace fonctionne en mode indentation
set viminfo='20,\"50
" Lire/écrite un fichier .viminfo, qui ne stocke pas plus de 50 lignes de
" registre
set history=50
" Garder un historique de 50 lignes de commandes
set ruler
" Toujours montrer la position du curseur
colorscheme desert
" Thème de couleur de vim
set textwidth=79
" Largeur des colonnes de texte = 79
set scrolloff=15
" Déplacement du scrool de la fenêtre 15 lignes avant le haut ou le bas
set autoindent
" Auto-indentation
set tabstop=2
" Déplacement de l'indentation
set shiftwidth=2
" Déplacement de l'insdentation
set expandtab
set modeline modelines=2


 " Only do this part when compiled with support for autocommands
if has("autocmd")
  augroup redhat
  autocmd!
  " In text files, always limit the width of text to 78 characters
  autocmd BufRead *.txt set tw=78
  " Lors de l'édition d'un fichier placer le curseur à son ancien emplacement
  autocmd BufReadPost *
  \ if line("'\"") > 0 && line ("'\"") <= line("$") |
  \   exe "normal! g'\"" |
  \ endif
  " don't write swapfile on most commonly used directories for NFS mounts or USB sticks
  autocmd BufNewFile,BufReadPre /media/*,/mnt/* set directory=~/tmp,/var/tmp,/tmp
  " start with spec file template
  autocmd BufNewFile *.spec 0r /usr/share/vim/vimfiles/template.spec
  augroup END
endif

if has("cscope") && filereadable("/usr/bin/cscope")
   set csprg=/usr/bin/cscope
   set csto=0
   set cst
   set nocsverb
   " add any database in current directory
   if filereadable("cscope.out")
      cs add cscope.out
   " else add database pointed to by environment
   elseif $CSCOPE_DB != ""
      cs add $CSCOPE_DB
   endif
   set csverb
endif

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

filetype plugin on

if &term=="xterm"
     set t_Co=8
     set t_Sb=[4%dm
     set t_Sf=[3%dm
endif

" Don't wake up system with blinking cursor:
" http://www.linuxpowertop.org/known.php
let &guicursor = &guicursor . ",a:blinkon0"
