#!/bin/bash

CWD=$(pwd)

echo ":: Le navigateur lynx va se lancer"
echo ":: Il faut taper '/rpmforge' pour trouver le paquet"
echo ":: Confirmer ensuite par la touche d (download)"
echo ":: Valider en tapant sur entrée puis quitter Lynx 'q' puis 'o'"
$CWD/chrono.sh
lynx http://apt.sw.be/redhat/el7/en/x86_64/rpmforge/RPMS/
